# Generated by Django 5.0.6 on 2024-06-23 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
