# Generated by Django 5.0.6 on 2024-06-30 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_schedule_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_time",
            field=models.TimeField(verbose_name="Конец занятия"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="location",
            field=models.CharField(blank=True, max_length=200, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_time",
            field=models.TimeField(verbose_name="Начало занятия"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название предмета"),
        ),
    ]
